source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'delyClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for delyClient
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'AlamofireImage'
  pod 'Kingfisher', '~> 5.0'

end
